# æœºåœºè®¢é˜…
proxy-providers:
  Pander:
    url: "æœºåœºè®¢é˜…"   # clash è®¢é˜…é“¾æ¥
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: ç›´è¿èŠ‚ç‚¹
    header:
      User-Agent:
      - "Clash"
      - "mihomo"
      - "Clash.meta"
    override:
      udp: true
      skip-cert-verify: true
#https://gh-proxy.com/raw.githubusercontent.com

# èŠ‚ç‚¹ä¿¡æ¯
proxies:
  - {name: ç›´è¿èŠ‚ç‚¹, type: direct, udp: true}

# å…¨å±€é…ç½® 
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: true
bind-address: "*"
ipv6: false
unified-delay: true
tcp-concurrent: true
log-level: warning
mode: rule
find-process-mode: 'off'
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 15
disable-keep-alive: false
profile:
  store-selected: true
  store-fake-ip: true


# æ§åˆ¶é¢æ¿
external-controller: 0.0.0.0:9090
secret: "dylan1010"
external-ui: "/etc/mihomo/run/ui"
external-ui-name: zashboard
external-ui-url: "https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip"

# å—…æ¢  ä½œç”¨ä¸æ˜¯å¾ˆå¤§ åœ¨è·¯ç”±è§„åˆ™åŒ¹é…çš„æ—¶å€™ å¦‚æœæ˜¯IP é€šè¿‡å—…æ¢åŒ¹é…å‡ºå¯¹åº” IP çš„åŸŸå
sniffer:
  enable: true
  sniff:
    # HTTP TLS QUIC å—…æ¢çš„ç«¯å£
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - "+.v2ex.com"
  skip-domain:
    - "rule-set:private_domain,cn_domain"
    - "dlg.io.mi.com"
    - "+.push.apple.com"
    - "+.apple.com"
    - "+.wechat.com"
    - "+.qpic.cn"
    - "+.qq.com"
    - "+.wechatapp.com"
    - "+.vivox.com"
    - "+.oray.com"
    - "+.sunlogin.net"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"

# DNSæ¨¡å—
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "rule-set:private_domain,cn_domain"
    - "+.services.googleapis.cn"
    - "+.xn--ngstr-lra8j.com"
    - "+.ntp.tencent.com"
    - "+.ntp1.aliyun.com"
    - "time.*.com"
    - "+.ntp.ntsc.ac.cn"
    - "+.pool.ntp.org"
    - "+.cn.ntp.org.cn"
  default-nameserver:
    - 221.5.203.98
    - 223.5.5.5
    - 119.29.29.29
  proxy-server-nameserver:
    - 221.5.203.98
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - 221.5.203.98
    - 223.5.5.5
    - 119.29.29.29
 
# å‡ºç«™ç­–ç•¥
# æ³¨æ„é”šç‚¹å¿…é¡»æ”¾åœ¨å¼•ç”¨çš„ä¸Šæ–¹,å¯ä»¥é›†ä¸­æŠŠé”šç‚¹å…¨éƒ¨æ”¾yamlçš„é¡¶éƒ¨ã€‚
# type:é€‰æ‹©èŠ‚ç‚¹çš„ç±»å‹ï¼›include-all:åŒ…å«æ‰€æœ‰çš„æœºåœºçš„è®¢é˜…é“¾æ¥ï¼ˆuse:æœºåœºåï¼‰;tolerance:, interval:æµ‹é€Ÿçš„é—´éš”
proxymain: &proxymain {type: select, proxies: [ğŸ‡­ğŸ‡° é¦™æ¸¯è‡ªåŠ¨, ğŸ‡¨ğŸ‡³ å°æ¹¾è‡ªåŠ¨, ğŸ‡¯ğŸ‡µ æ—¥æœ¬è‡ªåŠ¨, ğŸ‡¸ğŸ‡¬ ç‹®åŸè‡ªåŠ¨, ğŸ‡ºğŸ‡¸ ç¾å›½è‡ªåŠ¨, ğŸ—º ç¯çƒèŠ‚ç‚¹, ğŸš€ å…¨éƒ¨èŠ‚ç‚¹, ğŸš¥ ç›´è¿è®¿é—®]}
directmain: &directmain {type: select, proxies: [ğŸš¥ ç›´è¿è®¿é—®, ğŸ‡­ğŸ‡° é¦™æ¸¯è‡ªåŠ¨, ğŸ‡¨ğŸ‡³ å°æ¹¾è‡ªåŠ¨, ğŸ‡¯ğŸ‡µ æ—¥æœ¬è‡ªåŠ¨, ğŸ‡¸ğŸ‡¬ ç‹®åŸè‡ªåŠ¨, ğŸ‡ºğŸ‡¸ ç¾å›½è‡ªåŠ¨, ğŸ—º ç¯çƒèŠ‚ç‚¹, ğŸš€ å…¨éƒ¨èŠ‚ç‚¹]}
proxy-groups:
  - {name: ğŸªœ ç¿»å¢™ä»£ç†, <<: *proxymain}
  - {name: ğŸ Apple, <<: *directmain}
  - {name: ğŸ ApplePro, <<: *proxymain}
  - {name: ğŸ” Google, <<: *proxymain}
  - {name: â“‚ï¸ Microsoft, <<: *proxymain}
  - {name: â˜ï¸ OneDrive, <<: *directmain}
  - {name: ğŸ™ Develop, <<: *proxymain}
  - {name: ğŸ¤– Intelligence, type: select, proxies: [ğŸ‡¯ğŸ‡µ æ—¥æœ¬è‡ªåŠ¨, ğŸ‡ºğŸ‡¸ ç¾å›½è‡ªåŠ¨]}
  - {name: ğŸ’° Wallet, type: select, proxies: [ğŸ‡¨ğŸ‡³ å°æ¹¾è‡ªåŠ¨, ğŸš¥ ç›´è¿è®¿é—®, ğŸ‡­ğŸ‡° é¦™æ¸¯è‡ªåŠ¨, ğŸ‡¯ğŸ‡µ æ—¥æœ¬è‡ªåŠ¨, ğŸ‡¸ğŸ‡¬ ç‹®åŸè‡ªåŠ¨, ğŸ‡ºğŸ‡¸ ç¾å›½è‡ªåŠ¨, ğŸ—º ç¯çƒèŠ‚ç‚¹, ğŸš€ å…¨éƒ¨èŠ‚ç‚¹]}
  - {name: ğŸ§­ Speedtest, <<: *directmain}
  - {name: ğŸ“± Telegram, type: select, proxies: [ğŸ‡¸ğŸ‡¬ ç‹®åŸè‡ªåŠ¨, ğŸ‡­ğŸ‡° é¦™æ¸¯è‡ªåŠ¨, ğŸ‡¨ğŸ‡³ å°æ¹¾è‡ªåŠ¨, ğŸ‡¯ğŸ‡µ æ—¥æœ¬è‡ªåŠ¨, ğŸ‡ºğŸ‡¸ ç¾å›½è‡ªåŠ¨, ğŸ—º ç¯çƒèŠ‚ç‚¹, ğŸš€ å…¨éƒ¨èŠ‚ç‚¹]}
  - {name: ğŸ¸ Spotify, type: select, proxies: [ğŸ‡¨ğŸ‡³ å°æ¹¾è‡ªåŠ¨, ğŸš¥ ç›´è¿è®¿é—®, ğŸ‡­ğŸ‡° é¦™æ¸¯è‡ªåŠ¨, ğŸ‡¯ğŸ‡µ æ—¥æœ¬è‡ªåŠ¨, ğŸ‡¸ğŸ‡¬ ç‹®åŸè‡ªåŠ¨, ğŸ‡ºğŸ‡¸ ç¾å›½è‡ªåŠ¨, ğŸ—º ç¯çƒèŠ‚ç‚¹, ğŸš€ å…¨éƒ¨èŠ‚ç‚¹]}
  - {name: ğŸ“½ï¸ å›½å¤–æµåª’ä½“, type: select, proxies: [ğŸ“º æµåª’è‡ªåŠ¨, ç›´è¿èŠ‚ç‚¹]}
  - {name: ğŸµ TikTok, type: select, proxies: [ğŸ‡ºğŸ‡¸ ç¾å›½è‡ªåŠ¨, ç›´è¿èŠ‚ç‚¹]}
  - {name: ğŸ® æ¸¸æˆç›´è¿, <<: *directmain}
  - {name: ğŸ® æ¸¸æˆä»£ç†, <<: *proxymain}
  - {name: ğŸš¥ ç›´è¿è®¿é—®, type: select, proxies: [ç›´è¿èŠ‚ç‚¹, ğŸ‡­ğŸ‡° é¦™æ¸¯è‡ªåŠ¨, ğŸ‡¨ğŸ‡³ å°æ¹¾è‡ªåŠ¨, ğŸ‡¯ğŸ‡µ æ—¥æœ¬è‡ªåŠ¨, ğŸ‡¸ğŸ‡¬ ç‹®åŸè‡ªåŠ¨, ğŸ‡ºğŸ‡¸ ç¾å›½è‡ªåŠ¨, ğŸ—º ç¯çƒèŠ‚ç‚¹, ğŸš€ å…¨éƒ¨èŠ‚ç‚¹]}
  - {name: ğŸ  æ¼ç½‘ä¹‹é±¼, <<: *proxymain}

  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(é¦™æ¸¯|HK|Hong Kong|ğŸ‡­ğŸ‡°|HongKong))^((?!(ç¦åˆ©|301|0.1x|0.2x|0.3x|0.4x|0.5x|0.6x|0.7x|0.8x|0.9x|3x|4x|5x)).)*$"}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(æ—¥æœ¬|ğŸ‡¯ğŸ‡µ))^((?!(ç¦åˆ©|0.1x|0.2x|0.3x|0.4x|0.5x|0.6x|0.7x|0.8x|0.9x|3x|4x|5x)).)*$"}
  - {name: ğŸ‡¸ğŸ‡¬ ç‹®åŸè‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(æ–°åŠ å¡|ğŸ‡¸ğŸ‡¬))^((?!(ç¦åˆ©|301|0.1x|0.2x|0.3x|0.4x|0.5x|0.6x|0.7x|0.8x|0.9x|3x|4x|5x)).)*$"}
  - {name: ğŸ‡¨ğŸ‡³ å°æ¹¾è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(å°æ¹¾|ğŸ‡¹ğŸ‡¼))^((?!(ç¦åˆ©|0.1x|0.2x|0.3x|0.4x|0.5x|0.6x|0.7x|0.8x|0.9x|3x|4x|5x)).)*$"}
  - {name: ğŸ‡ºğŸ‡¸ ç¾å›½è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(ç¾å›½|ğŸ‡ºğŸ‡¸))^((?!(ç¦åˆ©|0.1x|0.2x|0.3x|0.4x|0.5x|0.6x|0.7x|0.8x|0.9x|3x|4x|5x)).)*$"}
  - {name: ğŸ“º æµåª’è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(NF|Disney|HBO|Hulu))^((?!(ç¦åˆ©|0.1x|0.2x|0.3x|0.4x|0.5x|0.6x|0.7x|0.8x|0.9x|3x|4x|5x)).)*$"}
  - {name: ğŸ—º ç¯çƒèŠ‚ç‚¹, type: select, include-all: true, filter: "^((?!(é¦™æ¸¯|HK|Hong Kong|ğŸ‡­ğŸ‡°|HongKong|æ—¥æœ¬|ğŸ‡¯ğŸ‡µ|æ–°åŠ å¡|ğŸ‡¸ğŸ‡¬|å°æ¹¾|ğŸ‡¹ğŸ‡¼|ç¾å›½|ğŸ‡ºğŸ‡¸|ç¦åˆ©|æ–°ç”¨æˆ·|ç›´è¿)).)*$"}
  - {name: ğŸš€ å…¨éƒ¨èŠ‚ç‚¹, type: select, include-all: true}

# è§„åˆ™åŒ¹é… æ­¤è§„åˆ™éƒ¨åˆ†æ²¡æœ‰åšé˜²æ³„éœ²å¤„ç†,å› ä¸ºå¼Šä¸¥é‡å¤§äºåˆ©ï¼æ³¨æ„é¡ºåº
rules:
  - RULE-SET,private_domain,ğŸš¥ ç›´è¿è®¿é—®
  - RULE-SET,per_direct,ğŸš¥ ç›´è¿è®¿é—®
  - RULE-SET,per_proxy,ğŸªœ ç¿»å¢™ä»£ç†

  - RULE-SET,category_ai_chat_notcn_domain,ğŸ¤– Intelligence
  - RULE-SET,per_proxy_intelligence,ğŸ¤– Intelligence

  - RULE-SET,category_dev_domain,ğŸ™ Develop
  - RULE-SET,developer_domain,ğŸ™ Develop
  - RULE-SET,linux_domain,ğŸ™ Develop
  - RULE-SET,per_proxy_develop,ğŸ™ Develop

  - RULE-SET,onedrive_domain,â˜ï¸ OneDrive
  - RULE-SET,synology_domain,ğŸš¥ ç›´è¿è®¿é—®
  - RULE-SET,telegram_domain,ğŸ“± Telegram
  - RULE-SET,paypal_domain,ğŸ’° Wallet
  - RULE-SET,speedtest_domain,ğŸ§­ Speedtest

  - RULE-SET,spotify_domain,ğŸ¸ Spotify
  - RULE-SET,tiktok_domain,ğŸµ TikTok

  - RULE-SET,per_proxy_media,ğŸ“½ï¸ å›½å¤–æµåª’ä½“
  - RULE-SET,globalmedia_domain,ğŸ“½ï¸ å›½å¤–æµåª’ä½“
  - RULE-SET,category_media_domain,ğŸ“½ï¸ å›½å¤–æµåª’ä½“
  - RULE-SET,category_media_cn_domain,ğŸš¥ ç›´è¿è®¿é—®
  - RULE-SET,chinamedia_domain,ğŸš¥ ç›´è¿è®¿é—®

  - RULE-SET,gamedownloadcn_domain,ğŸ® æ¸¸æˆç›´è¿
  - RULE-SET,category_games_cn_domain,ğŸ® æ¸¸æˆç›´è¿
  - RULE-SET,gamedownload_domain,ğŸ® æ¸¸æˆä»£ç†
  - RULE-SET,category_games_domain,ğŸ® æ¸¸æˆä»£ç†

  - RULE-SET,apple_domain,ğŸ Apple
  - RULE-SET,apple_notcn_domain,ğŸ ApplePr
  - RULE-SET,google_domain,ğŸ” Google
  - RULE-SET,microsoft_domain,â“‚ï¸ Microsoft

  - RULE-SET,proxy_domain,ğŸªœ ç¿»å¢™ä»£ç†
  - RULE-SET,gfw_domain,ğŸªœ ç¿»å¢™ä»£ç†
  - RULE-SET,geolocation_notcn_domain,ğŸªœ ç¿»å¢™ä»£ç†
  - RULE-SET,cn_domain,ğŸš¥ ç›´è¿è®¿é—®

  - RULE-SET,per_proxy_develop_ip,ğŸ™ Develop,no-resolve
  - RULE-SET,telegram_ip,ğŸ“± Telegram,no-resolve
  - RULE-SET,globalmedia_ip,ğŸ“½ï¸ å›½å¤–æµåª’ä½“,no-resolve
  - RULE-SET,chinamedia_ip,ğŸš¥ ç›´è¿è®¿é—®,no-resolve
  - RULE-SET,google_ip,ğŸ” Google,no-resolve
  - RULE-SET,apple_ip,ğŸ Apple,no-resolve
  - RULE-SET,cn_ip,ğŸš¥ ç›´è¿è®¿é—®
  - MATCH,ğŸ  æ¼ç½‘ä¹‹é±¼

#  - DOMAIN-SUFFIX,qichiyu.com,ğŸš€ é»˜è®¤ä»£ç†    # ä¸´æ—¶æ·»åŠ è§„åˆ™


# è§„åˆ™é›†
rule-anchor:    # è§„åˆ™é›†çš„é”šç‚¹
  # é”šç‚¹åå­—ï¼š&é”šç‚¹åå­—{type:å®šä¹‰ä»å“ªé‡Œè·å–(httpæ˜¯ç½‘ä¸Š,flieæ˜¯æœ¬åœ°), interval:æ›´æ–°æ—¶é—´, behavior:è§„åˆ™é›†å†…å®¹æ˜¯ä»€ä¹ˆæ ¼å¼çš„(è§„åˆ™é›†ä¸­æ˜¯IP(ipcidr)è¿˜æ˜¯åŸŸå(domain)è¿˜æ˜¯è€æ ¼å¼(classical)),format:å®šä¹‰æ–‡ä»¶æ˜¯ä»€ä¹ˆæ ¼å¼}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
rule-providers:
  # æœ¬åœ°å±€åŸŸç½‘
  private_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"}
  # ai
  category_ai_chat_notcn_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-chat-!cn.mrs"}
  # å¼€å‘
  category_dev_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-dev.mrs"}
  developer_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Developer/Developer_OCD_Domain.mrs"}
  linux_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/linux.mrs"}
  # google
  google_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"}
  google_ip: { <<: *ip, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs"}
  # å¾®è½¯
  onedrive_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs"}
  microsoft_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs"}
  # è‹¹æœ
  apple_notcn_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple%40cn.mrs"}
  apple_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.mrs"}
  apple_ip: { <<: *ip, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/apple.mrs"}
  # é‡‘è
  paypal_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs"}
  # telegram
  telegram_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs"}
  telegram_ip: { <<: *ip, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"}
  # åª’ä½“
  spotify_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/spotify.mrs"}
  tiktok_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs"}

  globalmedia_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/GlobalMedia/GlobalMedia_OCD_Domain.mrs"}
  globalmedia_ip: { <<: *ip, url: "https://gh-proxy.com/raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/GlobalMedia/GlobalMedia_OCD_IP.mrs"}
  category_media_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-media.mrs"}

  category_media_cn_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-media-cn.mrs"}
  chinamedia_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/ChinaMedia/ChinaMedia_OCD_Domain.mrs"}
  chinamedia_ip: { <<: *ip, url: "https://gh-proxy.com/raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/ChinaMedia/ChinaMedia_OCD_IP.mrs"}

  # å·¥å…·
  speedtest_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/speedtest.mrs"}
  synology_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/synology.mrs"}
  # æ¸¸æˆ
  gamedownloadcn_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Game/GameDownloadCN/GameDownloadCN_OCD_Domain.mrs"}
  category_games_cn_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-games%40cn.mrs"}
  gamedownload_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Game/GameDownload/GameDownload_OCD_Domain.mrs"}
  category_games_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-games.mrs"}
  # å…¨å±€
  proxy_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geosite/proxy.mrs"}
  gfw_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gfw.mrs"}
  geolocation_notcn_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"}
  cn_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"}
  cn_ip: { <<: *ip, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"}
  
  # ä¸ªäºº
  per_proxy_develop_ip: { <<: *ip, url: "https://gh-proxy.com/raw.githubusercontent.com/SlippinDylan/mihomoRules/master/MRS/mrs/Proxy-Develop-IP.mrs"}
  per_direct: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/SlippinDylan/mihomoRules/master/MRS/mrs/Direct.mrs"}
  per_proxy_develop: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/SlippinDylan/mihomoRules/master/MRS/mrs/Proxy-Develop.mrs"}
  per_proxy_intelligence: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/SlippinDylan/mihomoRules/master/MRS/mrs/Proxy-Intelligence.mrs"}
  per_proxy_media: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/SlippinDylan/mihomoRules/master/MRS/mrs/Proxy-Media.mrs"}
  per_proxy: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/SlippinDylan/mihomoRules/master/MRS/mrs/Proxy.mrs"}